Dahl tabs
omou-org/front-end pull request #609
Opened 2020-11-03 19:57 UTC by pswk1

Adjustments to tabs styling to match Figma specifications

2020-11-11 22:49 UTC, andrewjknapp requested changes
Hey Peter, I found a couple places in Omou where the old tabs are still there. These include the EnrollmentView.js and the class display after going through the Registration tab. I also was not sure how to test to see the LabelBadge that you added in. Let me know when you have updated these and I can finish this review. Thanks
![image](https://user-images.githubusercontent.com/16299570/98873175-b9d77c00-242c-11eb-8738-c27f9d6fdae3.png)
![image](https://user-images.githubusercontent.com/16299570/98873240-db386800-242c-11eb-9202-dff6d1f0a108.png)

2020-11-11 22:49 UTC, andrewjknapp commented on src/components/FeatureViews/Accounts/UserProfile.js
> +import { LabelBadge } from '../../../theme/ThemedComponents/Badge/LabelBadge';
I would recommend moving this to the bottom of your import statements to group all the material-ui imports together. Also use double quotes to match the other imports.

2020-11-13 00:12 UTC, pswk1 commented
@dhuangg @CalvinFronda 
Tagging here because Dahl tab migration (particularly Notes) is waiting on REST to GraphQL migration in Accounts &  EnrollmentView

2020-11-23 16:50 UTC, andrewjknapp approved these changes
You have addressed all of my comments, looks like this is good to merge.

2020-11-23 16:55 UTC, merged