Fixing front end
omou-org/front-end pull request #634
Opened 2020-11-26 04:03 UTC by clam1987

Started some fixes in front-end

2020-12-03 02:45 UTC, NeilAllavarpu requested changes

2020-12-03 02:45 UTC, NeilAllavarpu commented on src/components/FeatureViews/Courses/CourseManagementContainer.js
> +              startTime={availabilityList[0].startTime}
If `availabilityList` is an array, it might have multiple time slots so we should handle that accordingly instead of only using the first slot.

2020-12-03 02:45 UTC, NeilAllavarpu commented on src/components/FeatureViews/Registration/CourseRegistrationReceipt.js
> +			endTime: data.course.availabilityList[0].endTime,
See above

2020-12-03 02:45 UTC, NeilAllavarpu commented on src/components/FeatureViews/Registration/RegistrationCart/StudentRegistrationsEntry.js
> +						{moment(course.availabilityList[0].endTime, ["HH.mm"]).format("h:mm A")}
See above

2020-12-03 02:45 UTC, NeilAllavarpu commented on src/utils.js
> +    const duration = moment.duration(moment("2020-01-01T" + availabilityList[0].endTime).diff(moment("2020-01-01T" + availabilityList[0].startTime))).asHours();
See above.

2020-12-03 02:46 UTC, dhuangg requested changes
Right now you're only displaying one of the start/end times, duration, and day of week. we need to display all. Reach out to @katiebelleho for the design

2020-12-03 02:46 UTC, dhuangg commented on src/components/FeatureViews/Courses/CourseManagementContainer.js
> +              day={availabilityList[0].dayOfWeek}
we should be displaying all of these availabilities, not just one

2020-12-03 02:46 UTC, dhuangg commented on src/components/FeatureViews/Registration/RegistrationCart/StudentRegistrationsEntry.js
> +						{moment(course.availabilityList[0].startTime, ["HH.mm"]).format("h:mm A")}{" - "}
this is only listing one of the availabilities. we need to create a component that would display all of the availabilities

2020-12-03 02:46 UTC, dhuangg commented on src/utils.js
> +    const duration = moment.duration(moment("2020-01-01T" + availabilityList[0].endTime).diff(moment("2020-01-01T" + availabilityList[0].startTime))).asHours();
we should be listing all durations

2020-12-03 04:15 UTC, dhuangg commented
need to refactor query to query activeCourseAvailablities instead of courseAvailabilities

2020-12-04 01:38 UTC, NeilAllavarpu approved these changes

2020-12-04 01:39 UTC, merged