Google classroom integration
omou-org/front-end pull request #671
Opened 2020-12-13 20:53 UTC by ml5885

Added Google Classroom Integration. 

On sign in, a popup appears asking to log in with Google. In Course Management, a google icon appears next to the courses that are integrated with Google Classroom. In Class Enrollment, a new "Send Invite" button is added that sends a Google Classroom invitation.

2020-12-13 22:02 UTC, dhuangg requested changes
Overall good work, just make sure a few things for the next PR: 
1. Merge your changes into "development" not "master"
![Screen Shot 2020-12-13 at 1 44 12 PM](https://user-images.githubusercontent.com/12959959/102025293-c90f5980-3d4b-11eb-984a-e42a7af6aeb2.png)
2. Clean up your files when you're ready for a review - there was a lot of rogue console.logs and unnecessary variables

2020-12-13 22:02 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +	const onSuccess = (status) => {
rename "status" to "response"

2020-12-13 22:02 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        setResponse(status);
delete "setResponse(status)" no need to save this in state

2020-12-13 22:36 UTC, dhuangg reviewed
looks good - just push up the merge with dev and retest the whole flow to make sure everything is still functional. attach screenshots of flow if possible

2021-02-01 18:09 UTC, CalvinFronda reviewed
Just a few import errors. I haven't see the functionality just an overview review. We will discuss more on tuesday.

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/FeatureViews/Courses/ClassEnrollmentList.js
> +          {GoogleClassroomInviteStatusMessage}
This doesn't match your state. Should be. ```googleClassroomInviteStatusMessage``` (lowercase g)

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/FeatureViews/Courses/CourseManagementContainer.js
> +    useEffect(() => {
```useEffect``` is not imported from react. This will break if you run it.

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/FeatureViews/Courses/CourseManagementContainer.js
> +      var isIntegrated = false;
use ```let```

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/FeatureViews/Courses/CourseManagementContainer.js
> +                        googleClassCodem={googleClassCodem}
This isn't matching your props. change  ```googleClassCodem```  to   ```googleClassCode```

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        dispatch({
```dispatch``` is not imported

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/Navigation/AuthenticatedNavigationView.js
> +    useEffect(() => {
```useEffect``` is not imported

2021-02-01 18:09 UTC, CalvinFronda commented on src/components/Navigation/AuthenticatedNavigationView.js
> +			isBusinessDataValid ? <div className="Navigation">
```isBusinessDataValid``` is undefined

2021-03-08 06:01 UTC, andrewjknapp commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        // setGoogle_access_token(response.tokenObj.access_token);
Look into 'response.reloadAuthResponse()'. You can find one implementation here about halfway down the page https://dev.to/sivaneshs/add-google-login-to-your-react-apps-in-10-mins-4del

2021-03-28 01:39 UTC, dhuangg commented
- [ ] conditionally render the Google Classroom button
- [ ] on success of google login, we should do 3 things:
  - [ ] login to Omou using Jerry's new auth endpoint
  - [ ] login to Google Classroom using the same function as the admin settings page
  - [ ] add login token to redux using `dispatch(await setToken(tokenAuth.token, shouldSave));` 
    - [ ] dispatch object created with `const dispatch = useDispatch();`. you can import `useDispatch()` from redux

2021-03-28 23:14 UTC, dhuangg requested changes
some minor comments to help make the code more readable. I'd recommend to read over the enrollment row code again to make sure everything in there is readable/understandable. i'm a bit confused by what you're trying to do there a times and I think this is going to be one of the more important components that we'll need to maintain. @andrewjknapp take a read at the enrollment row and give your feedback too

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +            try {
put this try catch into its own function called "sendGoogleClassroomInvite()"

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +            console.log('Refreshing');
remove console.log

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +                    console.log(studentEmail);
remove console.log

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +                    const resp = await axios.get(
rename "resp" ot be more descriptive

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +                    const resp = await axios.post(
reanme "resp" to be more descriptive"

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +            inviteStatus == 'Unsent'
why are you checking for these 2 statuses? also put these 2 statuses into an explanatory variable

2021-03-28 23:14 UTC, dhuangg commented on src/components/FeatureViews/Courses/ClassEnrollmentRow.js
> +        let googleCourseID = getGoogleCourseID(
is this the omou courseId that has google classroom integration? if so, rename this variable to convey that more clearly

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavBar.js
> +    // const { signIn, loaded } = useGoogleLogin({
remove comments if not in use

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavBar.js
> +    const onSuccess = (response) => {
remove if not in use

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        console.log('Refresh Token runs');
remove console.log

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +            console.log('new auth Token ', newAuthRes.id.token);
ditto

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        console.log(
remove console.log

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +            console.log(
remove

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +    function getCourses() {
put this function higher up before it's called in the `useEffect()` on line 82 to help the reader

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +            sessionStorage.getItem('google_access_token')
put this condition into an explanatory variable to help the reader understand what and why you're checking for these conditions

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        if (google_courses === undefined || google_courses == null) {
why are you setting the courses in redux if google_courses is undefined or null?

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        console.log('gClassResp: ', gClassResp);
remove

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        console.log('Response.Access: ', response.tokenObj.access_token);
remove console logs

2021-03-28 23:14 UTC, dhuangg commented on src/components/Navigation/AuthenticatedNavigationView.js
> +        console.log(
remove console.logs

2021-03-29 02:38 UTC, dhuangg commented
closing this to continue on #759

2021-03-29 02:38 UTC, closed without merging