fix(single, all sessions edit), fix spacing and alignment
omou-org/front-end pull request #776
Opened 2021-05-18 02:07 UTC by juicekey

2021-05-26 00:55 UTC, dhuangg requested changes
yolo. glhf.

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionPopover.js
> -export const SessionPopover = ({
Why was this file deleted?

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/AllSessionsEdit.js
> +// import { SnackBarComponent } from '../../OmouComponents/SnackBarComponent';
delete comment

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/AllSessionsEdit.js
> +                // date: moment(sessionDate).format('YYYY-MM-DD'),
@clam1987 can you implement this for all courses conflicts check?

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/AllSessionsEdit.js
> +    // const snackBarData = {
@clam1987 implement this for all sessions edit

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SaveSessionEditsButton.js
> +// import {darkBlue, darkGrey} from "../../../theme/muiTheme";
remove comment

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SessionDetails.js
> +            >
you're using lines 168 - 176 twice - refactor to only use once

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SessionDetails.js
> +    const EditBadge = {
This should be a component instead of an object. since this takes in an binary state (either editing all sessions or editing a single session), you can make a prop that reflects that (e.g. `isSingleSessionEdit`)

Example usage: `<EditBadge isSingleSessionEdit={true}/>`

Example implementation:
```
const EditBadge = (editType) => (<Grid //grid props>
   <Typography //typography props>
     {`Editing ${ isSingleSession ? 'This Session' : 'All Sessions'}`}
  </Typography>
</Grid>);
```

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SessionDetails.js
> +                                    startSessionTime + ' - ' + endSessionTime
create an explanatory variable to quickly summarize what this string is

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SessionDetails.js
> +                            // <NavLink style={{ textDecoration: 'none' }} to={`/accounts/instructor/${instructor.user.id}`}>
we should still be linking the instructor's name to the instructor's profile

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SessionPopover.js
> +    <Grid item xs={5}> */}
delete comments

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionViewButtons.js
> +const SessionViewButtons = () => {
what's the difference between this and the "SessionOptions" component? choose one that's unused to delete

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SingleSessionEdit.js
> +            console.log(data);
delete console.log

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SingleSessionEdit.js
> +            // }
uncomment

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SingleSessionEdit.js
> +    const studentName = 'Timmeh';
flip bback to the fullName

2021-05-26 00:55 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SingleSessionEdit.js
> +        // console.log(moment(startSessionTime).isBefore(moment(endSessionTime)));
remove comment

2021-05-26 22:45 UTC, juicekey commented on src/components/FeatureViews/Scheduler/SessionPopover.js
> -export const SessionPopover = ({
Didn't you do that because the popover is now called something else?

2021-06-07 04:24 UTC, dhuangg requested changes
some last clean-up items + clarification needed on some of these~

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/AllSessionsEdit.js
> +                            courseConfirmationData='Jimmy'
why are we only passing in "Jimmy"?

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/EditSessionUtilComponents.js
> +                        <svg
make this icon its own component @clam1987

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/EditSessionUtilComponents.js
> +        setValue(e.format('YYYY-MM-DD[T]HH:mm'));
if you're using this `e.format()` twice, then make a const for it

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SaveSessionEditsButton.js
> +                                {courseConfirmationData}
what is this prop?

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SingleSessionEdit.js
> +    // ).name;
delete comments if not in use

2021-06-07 04:24 UTC, dhuangg commented on src/components/FeatureViews/Scheduler/SessionView/SingleSessionEdit.js
> +    // );
ditto

2021-06-21 23:23 UTC, merged